version: "3.3"
services:
  # Get ConstAddressDeployer compiled contract (JSON file)
  contracts-init:
    image: ghcr.io/topos-network/topos-smart-contracts:${TOPOS_MESSAGING_PROTOCOL_CONTRACTS_VERSION}
    container_name: contracts-init
    init: true
    volumes:
      - contracts:/usr/src/app/artifacts/contracts
    networks:
      - full-msg-protocol-infra-docker

  contracts-topos:
    image: ghcr.io/topos-network/topos-smart-contracts:${TOPOS_MESSAGING_PROTOCOL_CONTRACTS_VERSION}
    container_name: contracts-topos
    init: true
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY}
      - TOKEN_DEPLOYER_SALT=${TOKEN_DEPLOYER_SALT}
      - TOPOS_CORE_SALT=${TOPOS_CORE_SALT}
      - TOPOS_CORE_PROXY_SALT=${TOPOS_CORE_PROXY_SALT}
      - ERC20_MESSAGING_SALT=${ERC20_MESSAGING_SALT}
      - SUBNET_REGISTRATOR_SALT=${SUBNET_REGISTRATOR_SALT}
      - SUBNET_REGISTRATOR_CONTRACT_ADDRESS=${SUBNET_REGISTRATOR_CONTRACT_ADDRESS}
      - INCAL_HOST_PORT=${INCAL_HOST_PORT}
      - INCAL_CHAIN_ID=${INCAL_CHAIN_ID}
      - INCAL_LOGO_URL=${INCAL_LOGO_URL}
      - EDENA_HOST_PORT=${EDENA_HOST_PORT}
      - EDENA_CHAIN_ID=${EDENA_CHAIN_ID}
      - EDENA_LOGO_URL=${EDENA_LOGO_URL}
    command: bash -c "
      npm run deploy:topos-msg-protocol http://topos-node-1:8545 $$(cat /data/topos/data-1/consensus/validator.key) &&
      npm run deploy http://topos-node-1:8545 artifacts/contracts/topos-core/SubnetRegistrator.sol/SubnetRegistrator.json $SUBNET_REGISTRATOR_SALT 4000000 &&
      npm run register-subnet http://topos-node-1:8545 $SUBNET_REGISTRATOR_CONTRACT_ADDRESS Incal $INCAL_CHAIN_ID localhost:$INCAL_HOST_PORT INCA $INCAL_LOGO_URL $$(cat /data/incal/data-1/consensus/validator.key) &&
      npm run register-subnet http://topos-node-1:8545 $SUBNET_REGISTRATOR_CONTRACT_ADDRESS Edena $EDENA_CHAIN_ID localhost:$EDENA_HOST_PORT EDEN $EDENA_LOGO_URL $$(cat /data/edena/data-1/consensus/validator.key)"
    volumes:
      - topos-data:/data/topos
      - incal-data:/data/incal
      - edena-data:/data/edena
    depends_on:
      topos-node-1:
        condition: service_healthy
      incal-node-1:
        condition: service_healthy
      edena-node-1:
        condition: service_healthy
    networks:
      - full-msg-protocol-infra-docker

  contracts-incal:
    image: ghcr.io/topos-network/topos-smart-contracts:${TOPOS_MESSAGING_PROTOCOL_CONTRACTS_VERSION}
    container_name: contracts-incal
    init: true
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY}
      - TOKEN_DEPLOYER_SALT=${TOKEN_DEPLOYER_SALT}
      - TOPOS_CORE_SALT=${TOPOS_CORE_SALT}
      - TOPOS_CORE_PROXY_SALT=${TOPOS_CORE_PROXY_SALT}
      - ERC20_MESSAGING_SALT=${ERC20_MESSAGING_SALT}
      - SUBNET_REGISTRATOR_SALT=${SUBNET_REGISTRATOR_SALT}
    command: bash -c "
      npm run deploy:topos-msg-protocol http://incal-node-1:8545 $$(cat /data/incal/data-1/consensus/validator.key)"
    volumes:
      - incal-data:/data/incal
    depends_on:
      incal-node-1:
        condition: service_healthy
    networks:
      - full-msg-protocol-infra-docker

  contracts-edena:
    image: ghcr.io/topos-network/topos-smart-contracts:${TOPOS_MESSAGING_PROTOCOL_CONTRACTS_VERSION}
    container_name: contracts-edena
    init: true
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY}
      - TOKEN_DEPLOYER_SALT=${TOKEN_DEPLOYER_SALT}
      - TOPOS_CORE_SALT=${TOPOS_CORE_SALT}
      - TOPOS_CORE_PROXY_SALT=${TOPOS_CORE_PROXY_SALT}
      - ERC20_MESSAGING_SALT=${ERC20_MESSAGING_SALT}
      - SUBNET_REGISTRATOR_SALT=${SUBNET_REGISTRATOR_SALT}
    command: bash -c "
      npm run deploy:topos-msg-protocol http://edena-node-1:8545 $$(cat /data/edena/data-1/consensus/validator.key)"
    volumes:
      - edena-data:/data/edena
    depends_on:
      edena-node-1:
        condition: service_healthy
    networks:
      - full-msg-protocol-infra-docker

volumes:
  contracts:
