version: "3.3"
services:
  # Create keys and genesis
  fuji-init:
    image: ghcr.io/topos-protocol/polygon-edge:${TOPOS_EDGE_VERSION}
    container_name: fuji-init
    init: true
    command: ["init", "ibft"]
    environment:
      - CHAIN_ID=${FUJI_CHAIN_ID}
      - BOOTNODE_DOMAIN_NAME=fuji-node-1
    depends_on:
      contracts-init:
        condition: service_completed_successfully
    volumes:
      - fuji-data:/data
      - contracts:/contracts
    networks:
      - local-erc20-messaging-infra-docker

  fuji-sequencer:
    image: ghcr.io/topos-protocol/topos:${TOPOS_VERSION}
    container_name: fuji-sequencer
    init: true
    volumes:
      - contracts:/contracts
      - fuji-data:/data
    depends_on:
      tce-boot:
        condition: service_started
      contracts-topos:
        condition: service_completed_successfully
    entrypoint: ""
    command: bash -c "
      source /contracts/.env &&
      export SUBNET_CONTRACT_ADDRESS=0x895fDeD7A795d499fc352d79eD77527c2bf4a521 &&
      init.sh boot sequencer run"
    environment:
      - TOOLCHAIN_VERSION=stable
      - RUST_BACKTRACE=full
      - SUBNET_JSONRPC_ENDPOINT=${FUJI_JSON_RPC_ENDPOINT}
      - SUBNET_WS_JSONRPC_ENDPOINT=${FUJI_WS_JSON_RPC_ENDPOINT}
      - SUBNET_START_BLOCK=${FUJI_START_BLOCK}
      - TOPOS_LOCAL_SUBNET_ID=${FUJI_SUBNET_ID}
      - TOPOS_LOCAL_SUBNET_DATA_DIR=/data/data-1
      - TOPOS_BASE_TCE_API_URL=http://infra-tce-boot-1:1340
      - TOPOS_OTLP_SERVICE_NAME=local-fuji-sequencer
      - TOPOS_OTLP_AGENT=
    networks:
      - local-erc20-messaging-infra-docker

volumes:
  fuji-data:
