version: "3.3"
services:
  tce-boot:
    image: ghcr.io/topos-network/topos:${TOPOS_VERSION}
    init: true
    command:
      - "boot"
      - "tce"
      - "run"
    healthcheck:
      test: ./topos tce push-peer-list --node http://localhost:1340 --format json /tmp/shared/peer_ids.json
      interval: 15s
    volumes:
      - shared:/tmp/shared
    ports:
      - "9090"
      - "1340:1340"
    environment:
      - RUST_LOG=info,topos=info
      - TOOLCHAIN_VERSION=stable
      - RUST_BACKTRACE=full
      - SUBNET_JSONRPC_ENDPOINT=topos-node-1:8545
      - SUBNET_CONTRACT_ADDRESS=${TOPOS_CORE_CONTRACT_ADDRESS}
      - TOPOS_LOCAL_SUBNET_DATA_DIR=/data/data-1
      - TOPOS_BASE_TCE_API_URL=http://infra-tce-boot-1:1340
      - TOPOS_OTLP_SERVICE_NAME=local-topos-sequencer
      - TOPOS_OTLP_AGENT=https://grpc.otel-collector.telemetry.devnet-1.toposware.com
      - TCE_ECHO_SAMPLE_SIZE=4
      - TCE_READY_SAMPLE_SIZE=4
      - TCE_DELIVERY_SAMPLE_SIZE=4
      - TCE_ECHO_THRESHOLD=3
      - TCE_READY_THRESHOLD=1
      - TCE_DELIVERY_THRESHOLD=2
      - TOPOS_MINIMUM_TCE_CLUSTER_SIZE=2
    networks:
      - full-msg-protocol-infra-docker

  tce-peer:
    image: ghcr.io/topos-network/topos:${TOPOS_VERSION}
    command:
      - "peer"
      - "tce"
      - "run"
    init: true
    healthcheck:
      test: ./topos tce push-peer-list --node http://localhost:1340 --format json /tmp/shared/peer_ids.json && ./topos tce status --node http://localhost:1340
      interval: 5s
    volumes:
      - shared:/tmp/shared
    depends_on:
      tce-boot:
        condition: service_healthy
    ports:
      - "9090"
      - "1340"
    deploy:
      replicas: 4
    environment:
      - LOCAL_TEST_NET=true
      - RUST_LOG=info,topos=info
      - TCE_DB_PATH=/tmp/default-db
      - TCE_API_ADDR=0.0.0.0:1340
      - TOPOS_OTLP_SERVICE_NAME=local-tce-peer-node
      - TOPOS_OTLP_AGENT=https://grpc.otel-collector.telemetry.devnet-1.toposware.com
      - TCE_ECHO_SAMPLE_SIZE=4
      - TCE_READY_SAMPLE_SIZE=4
      - TCE_DELIVERY_SAMPLE_SIZE=4
      - TCE_ECHO_THRESHOLD=3
      - TCE_READY_THRESHOLD=1
      - TCE_DELIVERY_THRESHOLD=2
      - TOPOS_MINIMUM_TCE_CLUSTER_SIZE=2
    networks:
      - full-msg-protocol-infra-docker

volumes:
  shared:
