version: "3.3"
services:
  # Create keys and genesis
  incal-init:
    image: ghcr.io/topos-network/polygon-edge:${TOPOSWARE_EDGE_VERSION}
    container_name: incal-init
    init: true
    command: ["init"]
    environment:
      - CHAIN_ID=${INCAL_CHAIN_ID}
      - BOOTNODE_DOMAIN_NAME=incal-node-1
    depends_on:
      contracts-init:
        condition: service_completed_successfully
    volumes:
      - incal-node-1:/polygon-edge/data-1
      - incal-node-2:/polygon-edge/data-2
      - incal-node-3:/polygon-edge/data-3
      - incal-node-4:/polygon-edge/data-4
      - incal-genesis:/genesis
      - contracts:/contracts

  incal-node-1:
    image: ghcr.io/topos-network/polygon-edge:${TOPOSWARE_EDGE_VERSION}
    container_name: incal-node-1
    init: true
    command:
      - "server"
      - "--data-dir"
      - "/data"
      - "--chain"
      - "/genesis/genesis.json"
      - "--grpc-address"
      - "0.0.0.0:9632"
      - "--libp2p"
      - "0.0.0.0:1478"
      - "--jsonrpc"
      - "0.0.0.0:8545"
      - "--seal"
    depends_on:
      incal-init:
        condition: service_completed_successfully
    volumes:
      - incal-node-1:/data
      - incal-genesis:/genesis
    restart: on-failure
    ports:
      - "20002:8545"

  incal-node-2:
    image: ghcr.io/topos-network/polygon-edge:${TOPOSWARE_EDGE_VERSION}
    container_name: incal-node-2
    init: true
    command:
      - "server"
      - "--data-dir"
      - "/data"
      - "--chain"
      - "/genesis/genesis.json"
      - "--grpc-address"
      - "0.0.0.0:9632"
      - "--libp2p"
      - "0.0.0.0:1478"
      - "--jsonrpc"
      - "0.0.0.0:8545"
      - "--seal"
    depends_on:
      incal-init:
        condition: service_completed_successfully
    volumes:
      - incal-node-2:/data
      - incal-genesis:/genesis
    restart: on-failure

  incal-node-3:
    image: ghcr.io/topos-network/polygon-edge:${TOPOSWARE_EDGE_VERSION}
    container_name: incal-node-3
    init: true
    command:
      - "server"
      - "--data-dir"
      - "/data"
      - "--chain"
      - "/genesis/genesis.json"
      - "--grpc-address"
      - "0.0.0.0:9632"
      - "--libp2p"
      - "0.0.0.0:1478"
      - "--jsonrpc"
      - "0.0.0.0:8545"
      - "--seal"
    depends_on:
      incal-init:
        condition: service_completed_successfully
    volumes:
      - incal-node-3:/data
      - incal-genesis:/genesis
    restart: on-failure

  incal-node-4:
    image: ghcr.io/topos-network/polygon-edge:${TOPOSWARE_EDGE_VERSION}
    container_name: incal-node-4
    init: true
    command:
      - "server"
      - "--data-dir"
      - "/data"
      - "--chain"
      - "/genesis/genesis.json"
      - "--grpc-address"
      - "0.0.0.0:9632"
      - "--libp2p"
      - "0.0.0.0:1478"
      - "--jsonrpc"
      - "0.0.0.0:8545"
      - "--seal"
    depends_on:
      incal-init:
        condition: service_completed_successfully
    volumes:
      - incal-node-4:/data
      - incal-genesis:/genesis
    restart: on-failure

  incal-sequencer:
    image: ghcr.io/topos-network/topos:${TOPOS_VERSION}
    container_name: incal-sequencer
    init: true
    command:
      - "boot"
      - "sequencer"
      - "run"
    volumes:
      - incal-node-1:/data
    depends_on:
      tce-boot:
        condition: service_started
      contracts:
        condition: service_completed_successfully
    environment:
      - RUST_LOG=info,topos=debug
      - TOOLCHAIN_VERSION=stable
      - RUST_BACKTRACE=full
      - SUBNET_JSONRPC_ENDPOINT=incal-node-1:8545
      - SUBNET_CONTRACT_ADDRESS=${TOPOS_CORE_CONTRACT_ADDRESS}
      - TOPOS_LOCAL_SUBNET_DATA_DIR=/data
      - TOPOS_BASE_TCE_API_URL=http://infra-tce-peer-1:1340

volumes:
  incal-genesis:
  incal-node-1:
  incal-node-2:
  incal-node-3:
  incal-node-4:
