version: "3.3"
services:
  # Create keys and genesis
  topos-init:
    image: ghcr.io/topos-network/polygon-edge:${TOPOSWARE_EDGE_VERSION}
    container_name: topos-init
    init: true
    command: ["init", "polybft"]
    environment:
      - CHAIN_ID=${TOPOS_CHAIN_ID}
      - BOOTNODE_DOMAIN_NAME=topos-node-1
    depends_on:
      contracts-init:
        condition: service_completed_successfully
    volumes:
      - topos-data:/data
      - contracts:/contracts

  topos-node-1:
    image: ghcr.io/topos-network/polygon-edge:${TOPOSWARE_EDGE_VERSION}
    container_name: topos-node-1
    init: true
    command:
      - "server"
      - "--data-dir"
      - "/data/data-1"
      - "--chain"
      - "/data/genesis.json"
      - "--grpc-address"
      - "0.0.0.0:9632"
      - "--libp2p"
      - "0.0.0.0:1478"
      - "--jsonrpc"
      - "0.0.0.0:8545"
      - "--seal"
    depends_on:
      topos-init:
        condition: service_completed_successfully
    volumes:
      - topos-data:/data
    restart: on-failure
    ports:
      - "10002:8545"

  topos-node-2:
    image: ghcr.io/topos-network/polygon-edge:${TOPOSWARE_EDGE_VERSION}
    container_name: topos-node-2
    init: true
    command:
      - "server"
      - "--data-dir"
      - "/data/data-2"
      - "--chain"
      - "/data/genesis.json"
      - "--grpc-address"
      - "0.0.0.0:9632"
      - "--libp2p"
      - "0.0.0.0:1478"
      - "--jsonrpc"
      - "0.0.0.0:8545"
      - "--seal"
    depends_on:
      topos-init:
        condition: service_completed_successfully
    volumes:
      - topos-data:/data
    restart: on-failure

  topos-node-3:
    image: ghcr.io/topos-network/polygon-edge:${TOPOSWARE_EDGE_VERSION}
    container_name: topos-node-3
    init: true
    command:
      - "server"
      - "--data-dir"
      - "/data/data-3"
      - "--chain"
      - "/data/genesis.json"
      - "--grpc-address"
      - "0.0.0.0:9632"
      - "--libp2p"
      - "0.0.0.0:1478"
      - "--jsonrpc"
      - "0.0.0.0:8545"
      - "--seal"
    depends_on:
      topos-init:
        condition: service_completed_successfully
    volumes:
      - topos-data:/data
    restart: on-failure

  topos-node-4:
    image: ghcr.io/topos-network/polygon-edge:${TOPOSWARE_EDGE_VERSION}
    container_name: topos-node-4
    init: true
    command:
      - "server"
      - "--data-dir"
      - "/data/data-4"
      - "--chain"
      - "/data/genesis.json"
      - "--grpc-address"
      - "0.0.0.0:9632"
      - "--libp2p"
      - "0.0.0.0:1478"
      - "--jsonrpc"
      - "0.0.0.0:8545"
      - "--seal"
    depends_on:
      topos-init:
        condition: service_completed_successfully
    volumes:
      - topos-data:/data
    restart: on-failure

  topos-sequencer:
    image: ghcr.io/topos-network/topos:${TOPOS_VERSION}
    container_name: topos-sequencer
    init: true
    command:
      - "boot"
      - "sequencer"
      - "run"
    volumes:
      - topos-data:/data
    depends_on:
      tce-boot:
        condition: service_started
      contracts:
        condition: service_completed_successfully
    environment:
      - RUST_LOG=info,topos=debug
      - TOOLCHAIN_VERSION=stable
      - RUST_BACKTRACE=full
      - SUBNET_JSONRPC_ENDPOINT=topos-node-1:8545
      - SUBNET_CONTRACT_ADDRESS=${TOPOS_CORE_CONTRACT_ADDRESS}
      - TOPOS_LOCAL_SUBNET_DATA_DIR=/data/data-1
      - TOPOS_BASE_TCE_API_URL=http://infra-tce-peer-2:1340
      - TOPOS_OTLP_SERVICE_NAME=local-topos-sequencer
      - TOPOS_OTLP_AGENT=https://otel-collector.telemetry.devnet-1.toposware.com      

volumes:
  topos-data:
