version: "3.3"
services:
  tce-boot:
    image: ghcr.io/topos-protocol/topos:${TOPOS_VERSION}
    init: true
    command:
      - "boot"
      - "node"
      - "up"
    healthcheck:
      test: ./topos node status --node http://localhost:1340
      interval: 15s
    volumes:
      - shared:/tmp/shared
    ports:
      - "9090"
      - "1340:1340"
      - "4000:4000"
    environment:
      - RUST_LOG=info,topos=info
      - TOOLCHAIN_VERSION=stable
      - RUST_BACKTRACE=full
      - TCE_DB_PATH=/tmp/default-db
      - TCE_API_ADDR=0.0.0.0:1340
      - TCE_GRAPHQL_API_ADDR=0.0.0.0:4000
      - TCE_METRICS_API_ADDR=0.0.0.0:4001
      - TCE_LOCAL_KS=1 # 12D3KooWRhFCXBhmsMnur3up3vJsDoqWh4c39PKXgSWwzAzDHNLn
      - TOPOS_OTLP_SERVICE_NAME=local-tce-boot-node
      - TOPOS_OTLP_AGENT=https://grpc.otel-collector.telemetry.devnet-1.topos.technology
      - TCE_ECHO_SAMPLE_SIZE=4
      - TCE_READY_SAMPLE_SIZE=4
      - TCE_DELIVERY_SAMPLE_SIZE=4
      - TCE_ECHO_THRESHOLD=3
      - TCE_READY_THRESHOLD=1
      - TCE_DELIVERY_THRESHOLD=2
      - TOPOS_MINIMUM_TCE_CLUSTER_SIZE=3
    networks:
      - local-erc20-messaging-infra-docker

  tce-peer:
    image: ghcr.io/topos-protocol/topos:${TOPOS_VERSION}
    command:
      - "peer"
      - "node"
      - "up"
    init: true
    healthcheck:
      test: ./topos node status --node http://localhost:1340
      interval: 5s
    volumes:
      - shared:/tmp/shared
    depends_on:
      tce-boot:
        condition: service_healthy
    ports:
      - "9090"
      - "1340"
    deploy:
      replicas: 4
    environment:
      - LOCAL_TEST_NET=true
      - RUST_LOG=info,topos=info
      - TCE_DB_PATH=/tmp/default-db
      - TCE_API_ADDR=0.0.0.0:1340
      - TCE_GRAPHQL_API_ADDR=0.0.0.0:4000
      - TCE_METRICS_API_ADDR=0.0.0.0:4001
      - TOPOS_OTLP_SERVICE_NAME=local-tce-peer-node
      - TOPOS_OTLP_AGENT=https://grpc.otel-collector.telemetry.devnet-1.topos.technology
      - TCE_ECHO_SAMPLE_SIZE=4
      - TCE_READY_SAMPLE_SIZE=4
      - TCE_DELIVERY_SAMPLE_SIZE=4
      - TCE_ECHO_THRESHOLD=3
      - TCE_READY_THRESHOLD=1
      - TCE_DELIVERY_THRESHOLD=2
      - TOPOS_MINIMUM_TCE_CLUSTER_SIZE=3
    networks:
      - local-erc20-messaging-infra-docker

volumes:
  shared:
