services:
  tce-boot:
    image: ghcr.io/topos-network/topos:${TOPOS_VERSION}
    init: true
    command:
      - "boot"
      - "tce"
      - "run"
    healthcheck:
      test: ./topos tce push-peer-list --endpoint http://localhost:1340 --format json /tmp/shared/peer_ids.json
      interval: 15s
    volumes:
      - shared:/tmp/shared
    ports:
      - "9090"
      - "1340:1340"
    environment:
      - RUST_LOG=info,topos=info
      - TOOLCHAIN_VERSION=stable
      - RUST_BACKTRACE=full
      - TCE_DB_PATH=/tmp/default-db
      - TCE_API_ADDR=0.0.0.0:1340
      - TCE_LOCAL_KS=1 # 12D3KooWRhFCXBhmsMnur3up3vJsDoqWh4c39PKXgSWwzAzDHNLn
      - TCE_JAEGER_SERVICE_NAME=local-tce-boot-node
      - TCE_JAEGER_AGENT=https://otel-collector.telemetry.devnet-1.toposware.com
      - TCE_ECHO_SAMPLE_SIZE=6
      - TCE_READY_SAMPLE_SIZE=6
      - TCE_DELIVERY_SAMPLE_SIZE=6
      - TCE_ECHO_THRESHOLD=2
      - TCE_READY_THRESHOLD=2
      - TCE_DELIVERY_THRESHOLD=2

  tce-peer:
    image: ghcr.io/topos-network/topos:${TOPOS_VERSION}
    command:
      - "tce"
      - "run"
    init: true
    healthcheck:
      test: ./topos tce push-peer-list --endpoint http://localhost:1340 --format json /tmp/shared/peer_ids.json && ./topos tce status --endpoint http://localhost:1340
      interval: 5s
    volumes:
      - shared:/tmp/shared
    depends_on:
      tce-boot:
        condition: service_healthy
    ports:
      - "9090"
      - "1340"
    deploy:
      replicas: 15
    environment:
      - LOCAL_TEST_NET=true
      - RUST_LOG=info,topos=info
      - TCE_DB_PATH=/tmp/default-db
      - TCE_API_ADDR=0.0.0.0:1340
      - TCE_JAEGER_SERVICE_NAME=local-tce-peer-node
      - TCE_JAEGER_AGENT=https://otel-collector.telemetry.devnet-1.toposware.com
      - TCE_ECHO_SAMPLE_SIZE=6
      - TCE_READY_SAMPLE_SIZE=6
      - TCE_DELIVERY_SAMPLE_SIZE=6
      - TCE_ECHO_THRESHOLD=2
      - TCE_READY_THRESHOLD=2
      - TCE_DELIVERY_THRESHOLD=2

volumes:
  shared:
