[base]
name = "sequencer-goerli"
role = "sequencer"
subnet = "goerli-sequencer"

[sequencer]
subnet-contract-address = "0xd56dab17bd9b2f8f40d0c6435c3e04d477bd7ad311d749e1a9a7aa20fe2ee40f"
subnet-jsonrpc-http = "https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
tce-grpc-endpoint = "http://topos-node-1:1340"
