[base]
name = "sequencer-incal"
role = "sequencer"
subnet = "incal"

[sequencer]
subnet-contract-address = "0xA72935F69ff442a8FEC503e4bd6c4084372154C3"
subnet-jsonrpc-http = "http://incal-node-1:8545"
tce-grpc-endpoint = "http://topos-node-1:1340"
