[base]
name = "sequencer-incal"
role = "sequencer"
subnet = "incal"

[sequencer]
subnet-contract-address = "0x5904ef7B466E6d5190e6CcdAa9C7072Ca4C763b8"
subnet-jsonrpc-http = "http://incal-node-1:8545"
tce-grpc-endpoint = "http://topos-node-1:1340"
