[base]
name = "sequencer-incal"
role = "sequencer"
subnet = "incal"

[sequencer]
subnet-contract-address = "0x4fD352f266E184eB369f9B6C94Ee838577547688"
subnet-jsonrpc-http = "http://incal-node-1:8545"
tce-grpc-endpoint = "http://infra-tce-peer-2:1340"
