[base]
name = "sequencer-topos"
role = "sequencer"
# Replace that by `topos` when we have a solution to run only sequencer
subnet = "topos-sequencer"

[sequencer]
subnet-contract-address = "0x5904ef7B466E6d5190e6CcdAa9C7072Ca4C763b8"
subnet-jsonrpc-http = "http://topos-node-1:8545"
tce-grpc-endpoint = "http://topos-node-1:1340"
