[base]
name = "sequencer-topos"
role = "sequencer"
# Replace that by `topos` when we have a solution to run only sequencer
subnet = "topos-sequencer"

[sequencer]
subnet-contract-address = "0xA72935F69ff442a8FEC503e4bd6c4084372154C3"
subnet-jsonrpc-http = "http://topos-node-1:8545"
tce-grpc-endpoint = "http://topos-node-1:1340"
