version: "3.8"

services:
  visualizer:
    image: ghcr.io/blockscout/visualizer:${VISUALIZER_DOCKER_TAG:-latest}
    pull_policy: always
    restart: always
    container_name: "visualizer"
    env_file:
      - ./common-visualizer.env
    ports:
      - 8152:8050
    networks:
      - full-msg-protocol-infra-docker
