version: "3.8"

services:
  db:
    image: postgres:14
    restart: always
    container_name: "postgres"
    command: postgres -c 'max_connections=200'
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - 5432
    volumes:
      - explorer-db:/var/lib/postgresql/data/
    networks:
      - full-msg-protocol-infra-docker
