[base]
name = "boot"
role = "validator"
subnet = "topos"

[edge]

[tce]
db-path = "tce_rocksdb"
graphql-api-addr = "0.0.0.0:4030"
grpc-api-addr = "0.0.0.0:1340"
libp2p-api-addr = "0.0.0.0:9090"
metrics-api-addr = "0.0.0.0:3030"
minimum-tce-cluster-size = 3
boot-peers = "16Uiu2HAmV7JbuqnRCnGu8Y2MgA8XeBfuWHaLRQjvdtRZ3B24ynFU /dns4/tce-peer-1/tcp/9090/p2p/16Uiu2HAmV7JbuqnRCnGu8Y2MgA8XeBfuWHaLRQjvdtRZ3B24ynFU"