name: Run e2e tests

on:
  pull_request:
    branches:
      - main

jobs:
  e2e:
    uses: topos-protocol/e2e-tests/.github/workflows/frontend:erc20-messaging.yml@feat/make-workflows-reusuable
    with:
      local-erc20-messaging-infra-ref: "${{ github.head_ref }}"
