name: Run e2e tests

on:
  pull_request:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: topos-protocol
          repo: e2e-tests
          github_token: ${{ secrets.ROBOT_PAT_TRIGGER_E2E_WORKFLOWS }}
          workflow_file_name: frontend:erc20-messaging.yml
          ref: main
          wait_interval: 60
          # Remove topos-docker-tag when https://github.com/topos-protocol/topos/pull/386 is merged
          client_payload: '{ "local-erc20-messaging-infra-ref": "${{ github.head_ref }}", "topos-docker-tag": "pr-386" }'
