name: Run e2e tests

on:
  pull_request:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: topos-protocol/e2e-tests/.github/frontend:erc20-messaging.yml@main
        with:
          local-erc20-messaging-infra-ref: "${{ github.head_ref }}"
